owner-repo: &owner-repo
  owner-repo: palantir/godel-okgo-asset-compiles

excutor: &executor
  executor:
    name: go/golang-1_11
    <<: *owner-repo

version: 2.1

orbs:
  go: palantir/go@0.0.5
  godel: palantir/godel@0.0.2

workflows:
  version: 2
  verify-test-dist-publish:
    jobs:
      - godel/verify:
          name: verify
          <<: *executor
      - godel/test:
          name: test
          <<: *executor
      - godel/dist:
          name: dist
          <<: *executor
      - godel/bintray-publish:
          name: publish
          <<: *executor
          bintray-subject: palantir
          bintray-repo: releases
          bintray-product: godel-okgo-asset-compiles
          requires:
            - verify
            - test
            - dist
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$/
            branches:
              ignore: /.*/
